version: "3.9"
services:
  app:
    build: 
      dockerfile: ./dockerfile
    command:
      - gunicorn
      - recipes_project.wsgi:application
      - --bind
      - "0.0.0.0:8000"
    ports:
      - "8000:8000"
    restart: always
    volumes:
      - ./recipes_project/database:/app/database
    
    
    
    
    
    
    

